= Example Ecommerce Web Application in Clojure

== Functions
- Create users, login
- Customers can: create orders
- Staff and Managers can: manage orders, manage product inventory
- Managers can: manage users (delete users)

== Technologies
Full-stack application using Clojure/ClojureScript.

=== Clojure Backend
Using Clojure on the JVM for the backend.

* https://github.com/ring-clojure/ring[Ring], a HTTP server abtraction library which is abstracting the Eclipse Jetty web server.
* https://github.com/weavejester/integrant[Integrant] manages system state and configuration.
* https://github.com/metosin/reitit[Reitit] is a data-driven routing library which largely runs on top of Ring.
** reitit-ring, middleware to manage ring
** reitit-spec, data coercion
** reitit-swagger, sets up Swagger REST API documentation
* SQLite database using JDBC-based access with the https://github.com/seancorfield/next-jdbc[next.jdbc] wrapper.
** https://github.com/seancorfield/honeysql[Honey SQL] used to define SQL queries as Clojure data structures.

=== ClojureScript Frontend
Using ClojureScript as the frontend.
* Compiles to JavaScript using https://github.com/thheller/shadow-cljs[shadow-cljs].
	- Live-reload, REPL, npm integration
* https://reagent-project.github.io/[Reagent], the foremost React wrapper for ClojureScript.
* MUI components library using a https://github.com/arttuka/reagent-material-ui[reagent wrapper]

== Building
=== Requirements
This repo uses Clojure 1.11, you need the https://clojure.org/guides/deps_and_cli[Clojure CLI] installed.

=== Running
You can run the application using:

 $ clj -m ecommerce.system
 
or the alias:

 $ clj -A:server

The web app can then be accessed at `+http://localhost:3000/+`

==== REPL
In the repl:

 $ clj -A:dev
 
The system can be run with:

 $ user=> (go)

=== License & Attribution
Basic design and original setup of application from the https://github.com/prestancedesign/usermanager-reitit-example[usermanager-reitit-example github project by prestancedesign (Michael Salihi)] which itself is based on the https://github.com/seancorfield/usermanager-example[Sean Corfield's usermanager example].
** Both distributed under Apache Source License 2.0

==== License

Copyright 2023 Sammy Shea

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.Copyright (c) 20